### ISSUE TITLE
lowerCase

### ISSUE THREAD

**Issue by Akryum** [unjs/scule#19]
`HelloWorld` => `hello world`

**Comment by huynl-96** [comment]
Temporarily, I believe you can achieve it by having `kebabCase('HelloWorld', ' ')`.

As for improvement, I guess we could make `kebabCase` as a wrapper function, then change the function name (maybe `joinLowercase`).

**Comment by pi0** [comment]
Hi @Akryum sorry for coming back to this late. Do you remember the usecase you had in mind for this utility?

I think it is a good idea but not sure about the naming decision. `lowerCase('FooBar')` => `foobar` also makes sense sometimes for example.

**Comment by Akryum** [comment]
https://github.com/histoire-dev/histoire/blob/b53857fa190a098ce366cd8f082addf9142ad768/packages/histoire/src/node/search.ts#L110

**Comment by Akryum** [comment]
`case` has `lower()`: https://www.npmjs.com/package/case

**Comment by itpropro** [comment]
Hey @Akryum,
if you just need a type safe lowercase, I can recommend `uncapitalize` from [string-ts](https://github.com/gustavoguichard/string-ts).
There is also a PR here to add flatcase (#68).
