### ISSUE TITLE
Consider strz or string-ts for types

### ISSUE THREAD

**Issue by pi0** [unjs/scule#57]
We can consider simplify/improve types based on https://github.com/dilan-dio4/strz by @dilan-dio4 also https://github.com/gustavoguichard/string-ts by @gustavoguichard

**Comment by gustavoguichard** [comment]
I'd love to have some sort of collaboration between us all

**Comment by StevenJPx2** [comment]
What difference do all of these libraries have for me to pick one over the other? I'm actually kinda confused, cause I basically default to unjs packages for developing my own packages, but scule seems redundant compared to string-ts.

**Comment by pi0** [comment]
scule is smarter, smaller and more consistent across utils due to how spitting works, but feel free to use alternative libs if fit better of course 👍🏼 

Since now we exported more type helpers via #58 I guess we can cancel this idea.

**Comment by gustavoguichard** [comment]
@pi0 : for the sake of R&D I'd love to know what you mean by "smarter" and "more consistent".
As far as smaller I can tell this lib has a much smaller API surface, but string-ts is tree shakable ;)

Looking forward to your answer as it may improve the development of string-ts.

**Comment by pi0** [comment]
Quickly checking strz [(src)](https://github.com/dilan-dio4/strz/blob/main/src/split.ts#L10) splits by an explicit separator such as `-` while scule's core is the splitter that uses both known splitters and character case frequency changes `fooBar` will be splitter to `foo` + `bar`. This allows converting across conventions with no effort also is tree-shakable. I checked `string-ts` and it seems do the same splitting strategy 👍🏼 I guess scule is mainly focusing on minimal API and string-ts having more utils which can co-exists. Feel free to open a PR to the readme I would love to link `string-ts` as an alternative if you like to.

**Comment by gustavoguichard** [comment]
> I checked `string-ts` and it seems do the same splitting strategy

You mean same as scule, right?

Yeah, when this issue was posted I wanted to cooperate somehow but don't know how could they work together as I see both as good alternatives. Not sure about your roadmap so don't know if it would make sense to suggest another library or you are gonna be covering other methods to the point where one could choose either.

Maybe next time someone makes a request, if you don't plan to add that to scule's API I'd be happy to have string-ts tagged ;)

Thanks for your kind answer

**Comment by pi0** [comment]
Surely! I think at least for now scule's only objective will be casing utils.
